# Generated by Django 5.2 on 2025-11-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_customuserrole_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='codename',
        ),
    ]
